deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 0
  containers:
    - name: overseerr
      image:
        repository: sctx/overseerr
        tag: latest
      ports:
        - name: http
          containerPort: 80
      env:
        - name: PORT
          value: "80"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/Bucharest
        - name: LOG_LEVEL
          value: debug
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 2000m
          memory: 2000Mi
      volumeMounts:
        - name: storage
          mountPath: /app/config
          subPath: overseerr/config
  volumes:
    - name: storage
      type: pvc
      typeName: storage-pvc

infisicalSecrets:
  - name: infisical-certificates
    serviceTokenSecretName: service-token
    secretsPath: /certificates
    secretName: tls-secret
    secretType: kubernetes.io/tls

ingress:
  name: ingress
  hosts:
    - host: ovrs.mariusne.com
      paths:
        - path: "/"
          pathType: Prefix
          serviceName: service
          servicePort: http
  tls:
    secretName: tls-secret

pvcs:
  - name: storage-pvc
    storageClassName: local-path-persistent
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem

services:
  - name: service
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
